server:
  port: 8090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
spring:
  application:
    name: MASTER
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: userconfig
      port: 27017
      host: localhost
